spring:
  application:
    name: pos-system

  datasource:
    url: jdbc:mysql://localhost:3306/pos_local_db?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:heshansanjaya08@gmail.com}
    password: ${EMAIL_PASSWORD:usrpjmuhclajtuun}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

# OTP Configuration
otp:
  expiration-minutes: 10
  length: 6

jwt:
  secret-key: bG9jYWwtc2VjcmV0LWtleS1mb3ItZGV2ZWxvcG1lbnQtdGhhdC1pcy1sb25nLWVub3VnaA==
  expiration: 86400000

logging:
  level:
    com.codX.pos: DEBUG
    org.springframework.security: DEBUG
    com.codX.pos.service.impl.EmailServiceImpl: DEBUG
    org.springframework.mail: DEBUG
