spring:
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

jwt:
  secret-key: ${JWT_SECRET}

logging:
  level:
    com.codX.pos: INFO
    org.springframework.security: WARN
